name: WakaReadme CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: |
          # Clear existing cache
          docker builder prune --force

          # Build and run container (executes unit tests)
          docker compose -p waka-readme -f ./compose.yml up --no-color --pull always --build --force-recreate

          # Cleanup
          docker compose -p waka-readme -f ./compose.yml down --rmi all